# Generated by Django 4.0.3 on 2022-04-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_series_alter_book_options_book_series_volume_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='series_volume_number',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the number in the series this book falls- or leave blank', null=True),
        ),
    ]
