# Generated by Django 4.0.3 on 2022-04-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_remove_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-series', 'series_volume_number']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='current_holder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
